language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make test
after_success:
  - make docker_build
after_success:
  - PASSWORD=$DOCKER_PASSWORD make docker_build
